name: Cloud functional tests
on: [push, repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  databricks-tests-linux:
    name: Databricks test (Linux)
    runs-on: ubuntu-latest
    env:
      VCPKG_TARGET_TRIPLET: x64-linux
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      GEN: ninja
      DUCKDB_PLATFORM: linux_amd64
      BUILD_EXTENSION_TEST_DEPS: full
      DATABRICKS_WRITE_TEST_CATALOG: duckdb_write_testing

    steps:
      - name: Install required ubuntu packages
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq software-properties-common
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq ninja-build make gcc-multilib g++-multilib zip unzip build-essential checkinstall curl libz-dev openssh-client

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@v1.2.11 # Note: pinned due to GLIBC incompatibility in later releases
        with:
          key: ${{ github.job }}-${{ matrix.duckdb_arch }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

      - name: Configure OpenSSL for Rust
        run: |
          echo "OPENSSL_ROOT_DIR=`pwd`/build/release/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_DIR=`pwd`/build/release/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_USE_STATIC_LIBS=true" >> $GITHUB_ENV

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: databricks/setup-cli@main
        
      - name: Setup credentials
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DATABRICKS_TOKEN: 'op://testing-rw/databricks_free/token'
          DATABRICKS_ENDPOINT: 'op://testing-rw/databricks_free/endpoint'
          DATABRICKS_REGION: 'op://testing-rw/databricks_free/aws_region'

#      - name: Create Databricks config
#        run: |
#          mkdir -p ~/.databrickscfg
#          echo "[ DEFAULT ]" > ~/.databrickscfg
#          echo "host = $DATABRICKS_ENDPOINT" >> ~/.databrickscfg
#          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
#
#      - name: Configure Python
#        run: |
#          python3 -m venv venv
#          . ./venv/bin/activate
#          ./venv/bin/pip3 install -r scripts/requirements

#      - name: Generate random schema name
#        run: |
#          echo "DATABRICKS_WRITE_TEST_SCHEMA=test_schema_$(uuidgen | tr '[:upper:]' '[:lower:]' | tr '-' '_')" >> $GITHUB_ENV

#      - name: Load write test data
#        run: |
#          ./venv/bin/python3 scripts/copy_write_test_data.py $DATABRICKS_WRITE_TEST_CATALOG.source $DATABRICKS_WRITE_TEST_CATALOG.$DATABRICKS_WRITE_TEST_SCHEMA

      - name: Build extension
        run: |
          make release

      - name: Run tests
        run: |
          make test_release

#      - name: Clean up test data
#        if: always()
#        run: |
#          ./venv/bin/python3 scripts/clean_test_data.py duckdb_write_testing.$DATABRICKS_WRITE_TEST_SCHEMA